print("Введите сумму")
S = int(input())
print("Введите произведение")
P = int(input())
X = int((S - ((-S) ** 2 - 4 * P) ** 0.5) / 2)
Y = int((S + ((-S) ** 2 - 4 * P) ** 0.5) / 2)
print(f"{S} {P} -> {X} {Y}")